//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFIT_PLANS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENEFIT_PLANS()
        {
            this.PERSONAL = new HashSet<PERSONAL>();
        }
    
        public decimal BENEFIT_PLANS_ID { get; set; }
        public string PLAN_NAME { get; set; }
        public Nullable<decimal> DEDUCTABLE { get; set; }
        public Nullable<decimal> PERCENTAGE_COPAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAL> PERSONAL { get; set; }
    }
}
