//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYMENT_WORKING_TIME
    {
        public decimal EMPLOYMENT_WORKING_TIME_ID { get; set; }
        public Nullable<decimal> EMPLOYMENT_ID { get; set; }
        public Nullable<System.DateTime> YEAR_WORKING { get; set; }
        public Nullable<decimal> MONTH_WORKING { get; set; }
        public Nullable<decimal> NUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH { get; set; }
        public Nullable<decimal> TOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH { get; set; }
    
        public virtual EMPLOYMENT EMPLOYMENT { get; set; }
    }
}
