//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYMENT()
        {
            this.EMPLOYMENT_WORKING_TIME = new HashSet<EMPLOYMENT_WORKING_TIME>();
            this.JOB_HISTORY = new HashSet<JOB_HISTORY>();
        }
    
        public decimal EMPLOYMENT_ID { get; set; }
        public string EMPLOYMENT_CODE { get; set; }
        public string EMPLOYMENT_STATUS { get; set; }
        public Nullable<System.DateTime> HIRE_DATE_FOR_WORKING { get; set; }
        public string WORKERS_COMP_CODE { get; set; }
        public Nullable<System.DateTime> TERMINATION_DATE { get; set; }
        public Nullable<System.DateTime> REHIRE_DATE_FOR_WORKING { get; set; }
        public Nullable<System.DateTime> LAST_REVIEW_DATE { get; set; }
        public Nullable<decimal> NUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH { get; set; }
        public Nullable<decimal> PERSONAL_ID { get; set; }
    
        public virtual PERSONAL PERSONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYMENT_WORKING_TIME> EMPLOYMENT_WORKING_TIME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB_HISTORY> JOB_HISTORY { get; set; }
    }
}
