//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_HISTORY
    {
        public decimal JOB_HISTORY_ID { get; set; }
        public Nullable<decimal> EMPLOYMENT_ID { get; set; }
        public string DEPARTMENT { get; set; }
        public string DIVISION { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> THRU_DATE { get; set; }
        public string JOB_TITLE { get; set; }
        public string SUPERVISOR { get; set; }
        public string LOCATION { get; set; }
        public Nullable<short> TYPE_OF_WORK { get; set; }
    
        public virtual EMPLOYMENT EMPLOYMENT { get; set; }
    }
}
