//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAL()
        {
            this.EMPLOYMENT = new HashSet<EMPLOYMENT>();
        }
    
        public decimal PERSONAL_ID { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string SOCIAL_SECURITY_NUMBER { get; set; }
        public string DRIVERS_LICENSE { get; set; }
        public string CURRENT_ADDRESS_1 { get; set; }
        public string CURRENT_ADDRESS_2 { get; set; }
        public string CURRENT_CITY { get; set; }
        public string CURRENT_COUNTRY { get; set; }
        public Nullable<decimal> CURRENT_ZIP { get; set; }
        public string CURRENT_GENDER { get; set; }
        public string CURRENT_PHONE_NUMBER { get; set; }
        public string CURRENT_PERSONAL_EMAIL { get; set; }
        public string CURRENT_MARITAL_STATUS { get; set; }
        public string ETHNICITY { get; set; }
        public Nullable<short> SHAREHOLDER_STATUS { get; set; }
        public Nullable<decimal> BENEFIT_PLAN_ID { get; set; }
    
        public virtual BENEFIT_PLANS BENEFIT_PLANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYMENT> EMPLOYMENT { get; set; }
    }
}
